language: python
python:
    - '3.6'
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends texlive-base
    - sudo apt-get install -y --no-install-recommends texlive-latex-base
    - sudo apt-get install -y texlive-latex-recommended 
    - sudo apt-get install -y texlive-latex-extra
    - sudo apt-get install -y texlive-fonts-recommended
    - sudo apt-get install -y --no-install-recommends latexmk
    - sudo apt-get install -y --no-install-recommends graphviz
script:
    - 'export RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD)'
    - '[ "$RELEASE_VERSION" == "travis" ] && export RELEASE_VERSION="master" ' # for debug only
    - paver build_all
    - touch _build/html/.nojekyll
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: _build/html
    verbose: true
    on:
        branch: 
            - travis
            - master
