language: python
python:
    - '3.6'
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends texlive-base
    - sudo apt-get install -y --no-install-recommends texlive-latex-base
    - sudo apt-get install -y --no-install-recommends texlive-latex-recommended 
    - sudo apt-get install -y --no-install-recommends texlive-latex-extra
    - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
    - sudo apt-get install -y --no-install-recommends graphviz
script:
    - pip install -r requirements.txt
    - make html
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: _build/html
    verbose: true
    on:
        branch: travis
